groups: []

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: pcf-pipelines
  type: git
  source:
    uri: https://github.com/pivotal-cf/pcf-pipelines.git
    branch: master
    tag_filter: v0.23.5

resources:
- name: gcloud-pcf
  type: git
  source:
    uri: git@github.com:aoz-turk/gcloud-pcf.git
    branch: master
    private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEA3JY1PlcwQtI9Mol+40MOQYh3l16mBuEQzTTv172+CJaMLI6D
      T4tgxhLnDbN6G/Ldq/c/lEZXvl39nFjp8CJOseyarKwLSJB8ISrnqw1Z+rWWQ3b7
      VNOknwwAddUoesi4+llXtR/vB6NKCJ1gqVlqg/bgmIMnSS4i8AYS5e5iob5GxTVK
      GZxoiR7syXU1lzPyA7VnUAwHqdAmGO3pbojxgk4UzLxVXTNFA87qreEfpWGhAg5Q
      Axq4FfFeM0lp5rZJJki5qtQ2XXGIjakIrEFs+tNklJAQvRuwn5a7glPM+ommFyh7
      tORO/56EAa5PmLIlfBmNBsCKaErdaOlKL42E8QIDAQABAoIBAQCPwF/AWad81G/H
      QG1tgySGNn3hKnA+KWv+nxHyYZe3Fw0QeGtAak9NpcHnXuAj2Jj3WXCYm2LRD4WX
      3yXNNT5dmxiNkKzlxCrwnnpNMa1CwhXDr4VImYg9kd+26ouvwKEznQeYZNAsBRDZ
      Hl6A3mGY0Ek7erUebq+cBglIyJqEVjreh0t2g1xi845uxmBHDKXGsm7M1bjqYuJn
      L5hsB3msqRYCPhJsGsN0i2Y1w6lvXF1gKW3JykWA3HGVanUdZE9IxcMJqfgaUIbR
      +yDbNY6XMEKAqw3DVvp4b3TyUDJzAFszrIVGgmUCi0LCqBU0A7ssKWg4G6dNwjum
      9rrDJJ4FAoGBAPfSjjfutlnDJthYYmyMo+sBAg36j+wcmYg1NzOc4msHpyVDmFp0
      Kj6CM5Xg8OzYKQA3pa3daIYq0cG2JOH4HacLAi4g2nNX8fcQNmGaYAGOrxjiKGG+
      9qVudMETvRjcB6HOG2cqeooImu0LfsfG8cUmvLuxcvtpMU7OC+xgvn+7AoGBAOPd
      lSF9UWTQ6h+WsXWmQjIWdjNdsYpEYXzLwWftsPf+YPsn/Qt1dPHqNC/jX/HCkis4
      W9q3wkBVVqJPVf2gSxojD8K0pzsomIC1qpiZIkU96RmrxCnI2N3O9/OfxmfbC8VV
      7AeCab+Qi0f/GxLc4Hejk1NJhPib9gKF0sO8y1VDAoGBAK1AxW5y84bTeP+84qpS
      tHIh1UbiieWepPNliL8LifsbcY4KsKNkHPhwXBIHHUfnYtqlDK39YQqTOut7JFPZ
      +xkCCDcpfq8up5l6+xnHLCFKmD0ENwkG0TYcf4FQBF4xzSAgkGXSe7Kui2j3JV4T
      Roj3KPDrAKClDPSz9f/+Lo/rAoGAehBCCg2ao3nyYPeVmqN0hGZZ7Uw8hgf5fSOd
      OHIwwbhH9WLHf/LssYa3bAvOYrDLIlHviquzaEkOvqXnN5U9hgPQNooVp3AouZIX
      j+VAYX03uGO2EnggDDoJwz0MyKejl5Nee+tVgKQKqIe01hbyO8SpcA1LKO5LC7Dq
      ZaZl+gcCgYArH8JGQXUOQIRBpSqbbWtXFJpa/8DrwvMFkzsMijbkOScxffnG2Pcp
      kdXyyacZR1lRWWsgCmTytYCB1S7f7fyr6nFyY8u4DfwhIfYi3D0x/tQBwFpsaphM
      nAGpNAJKxg185vw4z3/D/e8kcCY3EP0wnje/ikTlv7kNNP07zqf0WA==
      -----END RSA PRIVATE KEY-----


- name: terraform-state
  type: gcs
  source:
    bucket: {{terraform_statefile_bucket}}
    json_key: {{gcp_service_account_key}}
    versioned_file: terraform.tfstate

- name: pivnet-opsmgr
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-manager
    product_version: {{opsman_major_minor_version}}
    sort_by: semver

- name: pivnet-elastic-runtime
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: elastic-runtime
    product_version: {{ert_major_minor_version}}
    sort_by: semver

jobs:
- name: wipe-env
  serial_groups: [terraform]
  ensure:
    put: terraform-state
    params:
      file: wipe-output/*.tfstate
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: terraform-state
  - task: wipe
    file: pcf-pipelines/install-pcf/gcp/tasks/wipe-env/task.yml
    params:
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_REGION: {{gcp_region}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      GCP_RESOURCE_PREFIX: {{gcp_resource_prefix}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_ZONE: {{gcp_zone_1}}

- name: upload-opsman-image
  plan:
  - get: pcf-pipelines
  - get: pivnet-opsmgr
    trigger: true
    params:
      globs:
      - "*GCP.yml"
  - task: upload
    file: pcf-pipelines/install-pcf/gcp/tasks/upload-opsman/task.yml
    params:
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_REGION: {{gcp_region}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}

- name: bootstrap-terraform-state
  serial: true
  plan:
  - get: pcf-pipelines
  - task: create-terraform-state
    params:
      TERRAFORM_STATEFILE_BUCKET: {{terraform_statefile_bucket}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
    file: pcf-pipelines/install-pcf/gcp/tasks/create-initial-terraform-state/task.yml

- name: create-infrastructure
  serial_groups: [terraform]
  ensure:
    put: terraform-state
    params:
      file: create-infrastructure-output/*.tfstate
  plan:
  - aggregate:
    - get: terraform-state
    - get: pcf-pipelines
    - get: pivnet-opsmgr
      passed: [upload-opsman-image]
      params:
        globs:
        - "*GCP.yml"
  - task: create-infrastructure
    file: pcf-pipelines/install-pcf/gcp/tasks/create-infrastructure/task.yml
    params:
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_REGION: {{gcp_region}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      GCP_ZONE_1: {{gcp_zone_1}}
      GCP_ZONE_2: {{gcp_zone_2}}
      GCP_ZONE_3: {{gcp_zone_3}}
      GCP_RESOURCE_PREFIX: {{gcp_resource_prefix}}
      GCP_STORAGE_BUCKET_LOCATION: {{gcp_storage_bucket_location}}
      PCF_ERT_DOMAIN: {{pcf_ert_domain}}
      SYSTEM_DOMAIN: {{system_domain}}
      APPS_DOMAIN: {{apps_domain}}
      POE_SSL_NAME1: {{poe_ssl_name1}}
      POE_SSL_CERT1: {{poe_ssl_cert1}}
      POE_SSL_KEY1: {{poe_ssl_key1}}
      DB_APP_USAGE_SERVICE_USERNAME: {{db_app_usage_service_username}}
      DB_APP_USAGE_SERVICE_PASSWORD: {{db_app_usage_service_password}}
      DB_AUTOSCALE_USERNAME: {{db_autoscale_username}}
      DB_AUTOSCALE_PASSWORD: {{db_autoscale_password}}
      DB_DIEGO_USERNAME: {{db_diego_username}}
      DB_DIEGO_PASSWORD: {{db_diego_password}}
      DB_NOTIFICATIONS_USERNAME: {{db_notifications_username}}
      DB_NOTIFICATIONS_PASSWORD: {{db_notifications_password}}
      DB_ROUTING_USERNAME: {{db_routing_username}}
      DB_ROUTING_PASSWORD: {{db_routing_password}}
      DB_UAA_USERNAME: {{db_uaa_username}}
      DB_UAA_PASSWORD: {{db_uaa_password}}
      DB_CCDB_USERNAME: {{db_ccdb_username}}
      DB_CCDB_PASSWORD: {{db_ccdb_password}}
      DB_ACCOUNTDB_USERNAME: {{db_accountdb_username}}
      DB_ACCOUNTDB_PASSWORD: {{db_accountdb_password}}
      DB_NETWORKPOLICYSERVERDB_USERNAME: {{db_networkpolicyserverdb_username}}
      DB_NETWORKPOLICYSERVERDB_PASSWORD: {{db_networkpolicyserverdb_password}}
      DB_NFSVOLUMEDB_USERNAME: {{db_nfsvolumedb_username}}
      DB_NFSVOLUMEDB_PASSWORD: {{db_nfsvolumedb_password}}
      DB_LOCKET_USERNAME: {{db_locket_username}}
      DB_LOCKET_PASSWORD: {{db_locket_password}}
      DB_SILK_USERNAME: {{db_silk_username}}
      DB_SILK_PASSWORD: {{db_silk_password}}
      DB_CLOUDSQLDB_TIER: {{db_cloudsqldb_tier}}

- name: configure-director
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: gcloud-pcf
    - get: pivnet-opsmgr
      passed: [create-infrastructure]
      params: {globs: []}
  - task: check-opsman-dns
    attempts: 3
    file: pcf-pipelines/install-pcf/gcp/tasks/check-opsman-dns/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
  - task: config-opsman-auth
    file: pcf-pipelines/tasks/config-opsman/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      OM_DECRYPTION_PWD: {{opsman_admin_password}}
  - task: configure-director
    file: gcloud-pcf/tasks/config-director/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      OPS_MGR_TRUSTED_CERTS: {{opsman_trusted_certs}}
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_REGION: {{gcp_region}}
      GCP_ZONE_1: {{gcp_zone_1}}
      GCP_ZONE_2: {{gcp_zone_2}}
      GCP_ZONE_3: {{gcp_zone_3}}
      GCP_RESOURCE_PREFIX: {{gcp_resource_prefix}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}

- name: deploy-director
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: pivnet-opsmgr
      passed: [configure-director]
      trigger: true
      params: {globs: []}
  - task: deploy-director
    file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_CLIENT_ID: ""
      OPSMAN_CLIENT_SECRET: ""
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}

- name: upload-ert
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: pivnet-opsmgr
      passed: [deploy-director]
      trigger: true
      params: {globs: []}
    - get: pivnet-product
      resource: pivnet-elastic-runtime
      params:
        globs:
        - "cf*.pivotal"
  - task: upload-tile
    file: pcf-pipelines/tasks/upload-product-and-stemcell/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      PIVNET_API_TOKEN: {{pivnet_token}}
      IAAS: "google"
      NO_PROXY: ""
      OM_IP: ""
      OPSMAN_CLIENT_ID: ""
      OPSMAN_CLIENT_SECRET: ""


  - task: stage-tile
    file: pcf-pipelines/tasks/stage-product/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_CLIENT_ID: ""
      OPSMAN_CLIENT_SECRET: ""